stuff:
  - name: slack-notifier
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/sso/ci-golang1.19-docker
      tag: dev
resource_types:
  - name: build-info
    type: registry-image
    source:
      repository: devtools-docker-local.artifactory.eng.vmware.com/vmware/runway/resourcetypes/buildinfo-resource
      tag: 3.0.0
  - name: coverity
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/coverity-resource
      tag: 2.9.0
